import random


def get_random_torture_method():
    """Returns a random torture method with full details"""

    torture_methods = [
        {
            "name": "The Brazen Bull",
            "description": "A hollow brass bull where victims were locked inside and a fire lit beneath. As the metal heated, the victim would be slowly roasted alive. Their screams would exit through tubes in the bull's mouth, sounding like the bellowing of a bull.",
            "origin": "Ancient Greece",
            "era": "6th Century BC",
        },
        {
            "name": "The Rack",
            "description": "Victims were tied to a wooden frame by their wrists and ankles. Rollers at either end were slowly turned, stretching the body until joints dislocated and limbs were torn from their sockets. Often used to extract confessions.",
            "origin": "Medieval Europe",
            "era": "Middle Ages",
        },
        {
            "name": "The Iron Maiden",
            "description": "A coffin-shaped device lined with iron spikes on the interior. The victim was placed inside and the door slowly closed, driving the spikes into the body. Positioned to avoid vital organs to prolong suffering.",
            "origin": "Germany",
            "era": "18th Century",
        },
        {
            "name": "Scaphism (The Boats)",
            "description": "Victim was trapped between two boats, with head, hands, and feet exposed. Force-fed milk and honey, then covered in the mixture to attract insects. Left in the sun, the victim would develop severe diarrhea, attracting more insects that would burrow into and consume the exposed flesh over days.",
            "origin": "Ancient Persia",
            "era": "5th Century BC",
        },
        {
            "name": "The Blood Eagle",
            "description": "Victim's ribs were severed from the spine and pulled outward to resemble eagle wings while still alive. The lungs were then extracted and laid across the 'wings.' Reserved for the most hated enemies.",
            "origin": "Viking Scandinavia",
            "era": "9th Century",
        },
        {
            "name": "Rat Torture",
            "description": "A cage containing live rats was placed on the victim's abdomen and heated from above. To escape the heat, the rats would burrow through the victim's flesh, eating their way into the body cavity.",
            "origin": "Medieval Europe/Asia",
            "era": "Various periods",
        },
        {
            "name": "Breaking Wheel",
            "description": "Victim was tied to a large wooden wheel. Their limbs were systematically broken with an iron hammer or cudgel, then the wheel was hoisted upright and left on display. Death could take days.",
            "origin": "Medieval Europe",
            "era": "Middle Ages - 18th Century",
        },
        {
            "name": "The Judas Cradle",
            "description": "Victim was suspended by ropes above a pyramid-shaped wooden or metal device, then slowly lowered onto its point which entered the anus, vagina, or scrotum. The torture could last days as the victim was repeatedly raised and lowered.",
            "origin": "Medieval Europe",
            "era": "16th Century",
        },
        {
            "name": "Flaying",
            "description": "The skin was systematically removed from the victim's body while they were still alive. Often started at the face or extremities and worked inward. Victims could remain conscious throughout most of the process.",
            "origin": "Ancient Assyria, Medieval Europe",
            "era": "Various periods",
        },
        {
            "name": "The Pear of Anguish",
            "description": "A metal device shaped like a pear inserted into the mouth, anus, or vagina. A screw mechanism would cause the 'petals' to slowly expand, tearing the orifice apart from the inside.",
            "origin": "Medieval Europe",
            "era": "Middle Ages",
        },
        {
            "name": "Bamboo Torture",
            "description": "Victim was tied over a bed of young bamboo shoots. The fast-growing bamboo (up to 3 feet per day) would slowly pierce through the victim's body, growing through them over several days.",
            "origin": "East Asia",
            "era": "Various periods",
        },
        {
            "name": "The Tub",
            "description": "Victim was placed in a wooden tub with only their head exposed. Force-fed milk and honey to induce diarrhea, they would sit in their own waste while insects bred and fed on the decomposing matter and living flesh.",
            "origin": "Medieval Europe",
            "era": "Middle Ages",
        },
        {
            "name": "Braiding (The Catherine Wheel)",
            "description": "Similar to the breaking wheel, but the victim's limbs were threaded through the wheel's spokes while still alive, 'braiding' them into the wheel structure before it was displayed publicly.",
            "origin": "Medieval Europe",
            "era": "Middle Ages",
        },
        {
            "name": "Crocodile Shears",
            "description": "A torture device with metal pincers formed like crocodile jaws. Heated until red-hot, they were used to clamp and tear flesh, often used on male genitals or female breasts.",
            "origin": "Medieval Europe",
            "era": "16th Century",
        },
        {
            "name": "The Spanish Tickler",
            "description": "A metal claw attached to a handle used to rake across the victim's flesh, tearing skin and muscle from bone. Multiple passes would reduce flesh to ribbons.",
            "origin": "Spain",
            "era": "Spanish Inquisition",
        },
        {
            "name": "Hanging, Drawing, and Quartering",
            "description": "Victim was hanged until nearly dead, then revived and disemboweled while conscious. Internal organs were burned before their eyes, then the body was beheaded and cut into four pieces for public display.",
            "origin": "England",
            "era": "13th-19th Century",
        },
        {
            "name": "The Strappado",
            "description": "Victim's hands were bound behind their back, then they were suspended by a rope attached to the wrists. Weights were often added to the feet, dislocating shoulders and causing excruciating pain.",
            "origin": "Medieval Europe",
            "era": "Middle Ages",
        },
        {
            "name": "The Pillory",
            "description": "While seemingly mild, victims locked in stocks or pillory were at the mercy of crowds who would pelt them with stones, rotten food, feces, or worse. Many died from injuries or infections.",
            "origin": "Medieval Europe",
            "era": "Middle Ages - 19th Century",
        },
        {
            "name": "Tongue Tearer",
            "description": "A scissor-like device clamped onto the tongue, with a screw mechanism that could either slowly crush it or rip it out entirely. Often used on blasphemers and heretics.",
            "origin": "Medieval Europe",
            "era": "Middle Ages",
        },
        {
            "name": "Breast Ripper",
            "description": "Four-clawed metal device heated red-hot and used to tear female breasts from the chest. Used primarily on women accused of witchcraft, adultery, or abortion.",
            "origin": "Medieval Europe",
            "era": "Middle Ages - Renaissance",
        },
        {
            "name": "The Heretic's Fork",
            "description": "A two-pronged fork strapped under the chin with points pressing into the throat and sternum. Prevented the victim from moving their head or sleeping without impaling themselves.",
            "origin": "Medieval Europe",
            "era": "Spanish Inquisition",
        },
        {
            "name": "Lead Sprinkler",
            "description": "A ladle-like device filled with molten lead, tar, boiling oil, or water. The substance was slowly dripped or poured onto the victim's body, causing severe burns and prolonged agony.",
            "origin": "Medieval Europe",
            "era": "Middle Ages",
        },
        {
            "name": "The Saw",
            "description": "Victim was hung upside down and slowly sawed in half vertically, starting from the groin. Being inverted ensured blood flow to the brain, keeping them conscious through most of the process.",
            "origin": "Medieval Europe, Ancient Rome",
            "era": "Various periods",
        },
        {
            "name": "Impalement",
            "description": "A long stake was inserted through the anus or vagina and slowly pushed through the body, carefully avoiding vital organs. The stake was then erected vertically with the victim still alive, death taking hours or days.",
            "origin": "Ottoman Empire, Romania",
            "era": "15th-16th Century",
        },
        {
            "name": "The Spanish Donkey",
            "description": "Victim was forced to straddle a sharp wooden wedge, sometimes with weights attached to their feet. The wedge would slowly cut upward through the groin over hours or days.",
            "origin": "Spain",
            "era": "Spanish Inquisition",
        },
        {
            "name": "Cement Shoes",
            "description": "Victim's feet were placed in buckets filled with wet cement. Once hardened, they were thrown into deep water to drown. The weight made escape impossible.",
            "origin": "American Mafia",
            "era": "20th Century",
        },
        {
            "name": "The Knee Splitter",
            "description": "A vise-like device lined with spikes clamped around the knee or elbow. As the screw was tightened, the spikes would penetrate deeper, eventually shattering the joint.",
            "origin": "Medieval Europe",
            "era": "Middle Ages",
        },
        {
            "name": "Necklacing",
            "description": "A rubber tire filled with gasoline was placed around the victim's chest and arms, then set ablaze. Death by burning could take up to 20 minutes.",
            "origin": "South Africa",
            "era": "1980s-1990s",
        },
        {
            "name": "The Head Crusher",
            "description": "The victim's chin was placed on a bottom bar while a cap-like top bar was screwed down onto their skull. Continued pressure would crush teeth into the jaw, then the skull itself would fracture and brain matter would leak out.",
            "origin": "Medieval Europe",
            "era": "Middle Ages",
        },
        {
            "name": "Burning at the Stake",
            "description": "Victim was tied to a wooden post surrounded by kindling and set aflame. Green wood was often used to produce more smoke, causing death by smoke inhalation before burning. Dry wood meant death by burning alive.",
            "origin": "Medieval Europe, Ancient Rome",
            "era": "Various periods",
        },
        {
            "name": "The Coffin",
            "description": "Victim was placed in a metal cage shaped like a human body, suspended in public. Exposure to elements, starvation, and attacks from birds and insects would slowly kill them over days.",
            "origin": "Medieval Europe",
            "era": "Middle Ages",
        },
        {
            "name": "Boiling Alive",
            "description": "Victim was placed in a large cauldron of water, oil, or tar which was gradually heated. Death occurred slowly from burns and eventual cooking of internal organs.",
            "origin": "Medieval Europe, Ancient Rome",
            "era": "Various periods",
        },
        {
            "name": "The Scold's Bridle",
            "description": "An iron muzzle locked around the head with a metal plate forced into the mouth, often studded with spikes that would pierce the tongue if the victim spoke. Used primarily on women.",
            "origin": "Scotland, England",
            "era": "16th-19th Century",
        },
        {
            "name": "Garrote",
            "description": "A metal collar tightened around the neck by a screw mechanism from behind. Some versions featured a spike that would slowly penetrate the spine as the collar tightened.",
            "origin": "Spain",
            "era": "Medieval - 20th Century",
        },
        {
            "name": "The Wooden Horse",
            "description": "Victim was forced to straddle a sharp-edged wooden beam, with weights attached to their feet. The edge would cut into the groin, sometimes severing the victim in half.",
            "origin": "Military punishment, various",
            "era": "18th-19th Century",
        },
        {
            "name": "Keelhauling",
            "description": "Victim was tied to a rope and dragged underneath a ship from one side to the other. Barnacles on the hull would shred flesh, and many drowned before reaching the other side.",
            "origin": "Dutch Navy",
            "era": "17th-18th Century",
        },
        {
            "name": "Lingchi (Death by a Thousand Cuts)",
            "description": "Systematic removal of small pieces of flesh over an extended period, sometimes days. The executioner would carefully avoid vital organs to prolong life and suffering as long as possible.",
            "origin": "China",
            "era": "10th Century - 1905",
        },
        {
            "name": "The Ducking Stool",
            "description": "Victim was strapped to a chair on a long wooden beam and repeatedly plunged into water. Used for suspected witches; survival proved guilt, drowning proved innocence.",
            "origin": "Medieval Europe",
            "era": "Middle Ages - 18th Century",
        },
        {
            "name": "Crucifixion",
            "description": "Victim was nailed or tied to a wooden cross and left to die. Death came from asphyxiation as the body weight made breathing increasingly difficult. Could take days.",
            "origin": "Ancient Rome, Persia",
            "era": "6th Century BC - 4th Century AD",
        },
        {
            "name": "The Iron Chair",
            "description": "A chair covered in spikes on all surfaces. The victim was strapped in and sometimes a fire was lit beneath. Weight and movement drove the spikes deeper.",
            "origin": "Medieval Europe",
            "era": "Middle Ages",
        },
        {
            "name": "Thumbscrews",
            "description": "A vise-like device that crushed fingers or toes. As the screw tightened, bones would splinter and eventually shatter. Often used to extract confessions.",
            "origin": "Medieval Europe",
            "era": "Middle Ages",
        },
        {
            "name": "The Breast Auger",
            "description": "A large screw-like device bore into the female breast, slowly drilling through tissue. Often heated red-hot before use.",
            "origin": "Medieval Europe",
            "era": "Middle Ages",
        },
        {
            "name": "Quartering by Horses",
            "description": "Each of the victim's limbs was tied to a separate horse, which were then driven in opposite directions, tearing the body apart. Sometimes required multiple attempts.",
            "origin": "Medieval Europe",
            "era": "Middle Ages",
        },
        {
            "name": "The Choke Pear",
            "description": "Similar to the Pear of Anguish, this device expanded inside the mouth, rectum, or vagina. The expanding segments had sharp edges that would tear and rend tissue.",
            "origin": "Medieval Europe",
            "era": "16th Century",
        },
        {
            "name": "Picquet",
            "description": "Victim was forced to stand on one foot on a pointed stake while weights were attached to the other foot. Exhaustion would cause them to impale their standing foot deeper.",
            "origin": "Military punishment, Prussia",
            "era": "17th-18th Century",
        },
        {
            "name": "The Wheel Barrow",
            "description": "Victim's legs were placed in holes in a board while bent over a barrel. They were beaten on the back and buttocks with rods or whips, often until crippled or dead.",
            "origin": "Colonial America",
            "era": "17th-18th Century",
        },
        {
            "name": "Running the Gauntlet",
            "description": "Victim was forced to run between two rows of people who beat them with sticks, clubs, or whips. Multiple runs were common, often resulting in death from injuries.",
            "origin": "Military punishment, various",
            "era": "17th-19th Century",
        },
        {
            "name": "The Shin Crusher",
            "description": "A wooden or metal frame lined with spikes clamped around the lower leg. As it was tightened, the spikes would pierce flesh and eventually shatter the bones.",
            "origin": "Medieval Europe",
            "era": "Middle Ages",
        },
        {
            "name": "The Boot",
            "description": "Victim's leg was placed in a wooden or metal boot. Wedges were hammered between the boot and leg, slowly crushing flesh and bone. Alternatively, hot oil was poured inside.",
            "origin": "Scotland",
            "era": "16th-17th Century",
        },
        {
            "name": "White Torture",
            "description": "Victim was kept in a completely white room with white clothes, white food, and no human contact. Sensory deprivation would cause psychological breakdown and hallucinations within days.",
            "origin": "Iran",
            "era": "20th-21st Century",
        },
        {
            "name": "Chinese Water Torture",
            "description": "Victim was immobilized while water slowly dripped onto their forehead. The psychological torment of the constant dripping in the same spot would drive victims insane.",
            "origin": "Allegedly China (disputed)",
            "era": "Unknown",
        },
        {
            "name": "The Witch's Chair",
            "description": "A chair covered in spikes where suspected witches were bound. Weight and exhaustion would cause them to sink onto the spikes. Sometimes heated from below.",
            "origin": "Medieval Europe",
            "era": "Middle Ages - Renaissance",
        },
        {
            "name": "The Tongue Slicer",
            "description": "A blade mechanism that would slowly slice the tongue lengthwise or crosswise. Used on those convicted of blasphemy or lying.",
            "origin": "Medieval Europe",
            "era": "Middle Ages",
        },
        {
            "name": "The Foot Press",
            "description": "Feet were placed in a frame and progressively tightened, crushing the bones. Iron plates were sometimes heated and placed on top for additional torture.",
            "origin": "Various",
            "era": "Middle Ages - 18th Century",
        },
        {
            "name": "Anal Impalement",
            "description": "A wooden stake was carefully inserted through the rectum and pushed through the body, avoiding vital organs. The victim would live for days impaled on the vertical stake.",
            "origin": "Romania (Vlad the Impaler)",
            "era": "15th Century",
        },
    ]

    return random.choice(torture_methods)
